/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import model.CPU;
import model.Human;
import model.Konane;
import model.KonaneLocal;
import model.Player;


/**
 *
 * @author Caedes
 */
public class MainWindow extends javax.swing.JFrame {
    
    private Konane game;
        
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.setTitle("Konane");
	//this.setSize(1200,1200);              //Change la taille 
        //this.setLocationRelativeTo(null);     //Change la localition de la fenetre
        //this.setResizable(false);             //Empeche le redimensionnement
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_icon = new javax.swing.JToolBar();
        GameIcon = new javax.swing.JButton();
        OnlineIcon = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SaveIcon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        RulesIcon = new javax.swing.JButton();
        ScorePanel = new javax.swing.JPanel();
        LabelP1 = new javax.swing.JLabel();
        LabelP2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        AbandJ1 = new javax.swing.JButton();
        AbandJ2 = new javax.swing.JButton();
        scoreJ1 = new javax.swing.JTextField();
        scoreJ2 = new javax.swing.JTextField();
        labelscoreJ1 = new javax.swing.JLabel();
        labelscoreJ2 = new javax.swing.JLabel();
        colorJ1_panel = new javax.swing.JPanel();
        colorJ2_panel = new javax.swing.JPanel();
        GamePanel = new javax.swing.JPanel();
        Menu_Main = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NewGameButton = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        IAButton = new javax.swing.JMenuItem();
        LoadGameButton = new javax.swing.JMenuItem();
        SaveGameButton = new javax.swing.JMenuItem();
        CloseButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MoveHelpingButton = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        RulesButton = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu_icon.setRollover(true);

        GameIcon.setText("NewGame");
        GameIcon.setFocusable(false);
        GameIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GameIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Menu_icon.add(GameIcon);

        OnlineIcon.setText("Online");
        OnlineIcon.setFocusable(false);
        OnlineIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OnlineIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OnlineIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineIconActionPerformed(evt);
            }
        });
        Menu_icon.add(OnlineIcon);
        OnlineIcon.getAccessibleContext().setAccessibleDescription("Play online");

        jButton1.setText("Load");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Menu_icon.add(jButton1);

        SaveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/document-save.png"))); // NOI18N
        SaveIcon.setFocusable(false);
        SaveIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveIconActionPerformed(evt);
            }
        });
        Menu_icon.add(SaveIcon);
        Menu_icon.add(jSeparator1);

        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Menu_icon.add(jCheckBox1);

        jLabel1.setText("  Assistance  ");
        Menu_icon.add(jLabel1);
        Menu_icon.add(jSeparator2);

        RulesIcon.setText("Règles");
        RulesIcon.setFocusable(false);
        RulesIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RulesIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RulesIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesIconActionPerformed(evt);
            }
        });
        Menu_icon.add(RulesIcon);

        LabelP1.setText("Joueur1");

        LabelP2.setText("Joueur2");

        AbandJ1.setText("Abandonner");

        AbandJ2.setText("Abandonner");

        scoreJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreJ2ActionPerformed(evt);
            }
        });

        labelscoreJ1.setText("score :");

        labelscoreJ2.setText("score :");

        javax.swing.GroupLayout colorJ1_panelLayout = new javax.swing.GroupLayout(colorJ1_panel);
        colorJ1_panel.setLayout(colorJ1_panelLayout);
        colorJ1_panelLayout.setHorizontalGroup(
            colorJ1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        colorJ1_panelLayout.setVerticalGroup(
            colorJ1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout colorJ2_panelLayout = new javax.swing.GroupLayout(colorJ2_panel);
        colorJ2_panel.setLayout(colorJ2_panelLayout);
        colorJ2_panelLayout.setHorizontalGroup(
            colorJ2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        colorJ2_panelLayout.setVerticalGroup(
            colorJ2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ScorePanelLayout = new javax.swing.GroupLayout(ScorePanel);
        ScorePanel.setLayout(ScorePanelLayout);
        ScorePanelLayout.setHorizontalGroup(
            ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScorePanelLayout.createSequentialGroup()
                .addGroup(ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScorePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(ScorePanelLayout.createSequentialGroup()
                        .addGroup(ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScorePanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AbandJ1)
                                    .addComponent(colorJ1_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ScorePanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AbandJ2)
                                    .addComponent(colorJ2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ScorePanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScorePanelLayout.createSequentialGroup()
                                        .addGroup(ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelscoreJ1)
                                            .addComponent(scoreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(ScorePanelLayout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addGroup(ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelscoreJ2)
                                                .addComponent(scoreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(ScorePanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(LabelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ScorePanelLayout.setVerticalGroup(
            ScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScorePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LabelP1)
                .addGap(28, 28, 28)
                .addComponent(labelscoreJ1)
                .addGap(5, 5, 5)
                .addComponent(scoreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorJ1_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(AbandJ1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(LabelP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(labelscoreJ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scoreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(colorJ2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(AbandJ2)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Partie");

        NewGameButton.setText("Nouvelle Partie...           F1");
        NewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameButtonActionPerformed(evt);
            }
        });
        jMenu1.add(NewGameButton);

        jMenuItem1.setText("Jouer en ligne...             F2");
        jMenu1.add(jMenuItem1);

        IAButton.setText("Choix de l'IA...                 F3");
        IAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IAButtonActionPerformed(evt);
            }
        });
        jMenu1.add(IAButton);

        LoadGameButton.setText("Charger partie...             F4");
        LoadGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGameButtonActionPerformed(evt);
            }
        });
        jMenu1.add(LoadGameButton);

        SaveGameButton.setText("Sauvegarder...                F6");
        SaveGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveGameButtonActionPerformed(evt);
            }
        });
        jMenu1.add(SaveGameButton);

        CloseButton.setText("Quitter...                           F9");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jMenu1.add(CloseButton);

        Menu_Main.add(jMenu1);

        jMenu2.setText("Propriétés");

        MoveHelpingButton.setSelected(true);
        MoveHelpingButton.setText("Aide aux mouvements");
        jMenu2.add(MoveHelpingButton);

        Menu_Main.add(jMenu2);

        jMenu3.setText("Aide");
        jMenu3.setActionCommand("");

        RulesButton.setText(" Règles");
        jMenu3.add(RulesButton);

        AboutMenu.setText("A propos");
        jMenu3.add(AboutMenu);

        Menu_Main.add(jMenu3);

        setJMenuBar(Menu_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameButtonActionPerformed
        GameCreating JCreateGame = new GameCreating(this, this);
        
    }//GEN-LAST:event_NewGameButtonActionPerformed

    private void SaveGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveGameButtonActionPerformed
        LoadOrSave JSave = new LoadOrSave(this,1);
        JSave.setTitle("Sauvegarder en");
        JSave.setVisible(true);
    }//GEN-LAST:event_SaveGameButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void OnlineIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OnlineIconActionPerformed

    private void SaveIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveIconActionPerformed
        LoadOrSave JSave = new LoadOrSave(this,1);
        JSave.setTitle("Sauvegarder en");
        JSave.setVisible(true);
    }//GEN-LAST:event_SaveIconActionPerformed

    private void IAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IAButtonActionPerformed
        IAChoosing JIAChoose = new IAChoosing(this);
    }//GEN-LAST:event_IAButtonActionPerformed

    private void RulesIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RulesIconActionPerformed

    private void LoadGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGameButtonActionPerformed
        LoadOrSave JLoad = new LoadOrSave(this,0);
        JLoad.setTitle("Charger en");
        JLoad.setVisible(true);
    }//GEN-LAST:event_LoadGameButtonActionPerformed

    private void scoreJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreJ2ActionPerformed

    public void beginGame(String p_white, String p_black, int nbCase, int typeP1, int typeP2){
        
        Player Jp1 = null;
        Player Jp2 = null;
        
        if(typeP1 == 0) {
            Jp1 = new Human(p_white);
            Jp2 = new CPU(p_black);
        }
        else {
            Jp1 = new CPU(p_white);
            Jp2 = new Human(p_black);
        }
        this.game = new KonaneLocal(Jp1, Jp2, nbCase, typeP1, typeP2);
        
        BoardPanel boardPanel = new BoardPanel(nbCase);
        this.GamePanel.add(boardPanel);
        //JLabel test = new JLabel("lol");
        //this.GamePanel.add(test);
        //this.GamePanel.setBackground(Color.red);
        
        this.ScorePanel.setVisible(true);
        this.GamePanel.setVisible(true);
        this.LabelP1.setText(p_white);
        this.LabelP2.setText(p_black);
        this.colorJ1_panel.setBackground(Color.white);
        this.colorJ2_panel.setBackground(Color.black);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbandJ1;
    private javax.swing.JButton AbandJ2;
    private javax.swing.JMenuItem AboutMenu;
    private javax.swing.JMenuItem CloseButton;
    private javax.swing.JButton GameIcon;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JMenuItem IAButton;
    private javax.swing.JLabel LabelP1;
    private javax.swing.JLabel LabelP2;
    private javax.swing.JMenuItem LoadGameButton;
    private javax.swing.JMenuBar Menu_Main;
    private javax.swing.JToolBar Menu_icon;
    private javax.swing.JCheckBoxMenuItem MoveHelpingButton;
    private javax.swing.JMenuItem NewGameButton;
    private javax.swing.JButton OnlineIcon;
    private javax.swing.JMenuItem RulesButton;
    private javax.swing.JButton RulesIcon;
    private javax.swing.JMenuItem SaveGameButton;
    private javax.swing.JButton SaveIcon;
    private javax.swing.JPanel ScorePanel;
    private javax.swing.JPanel colorJ1_panel;
    private javax.swing.JPanel colorJ2_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelscoreJ1;
    private javax.swing.JLabel labelscoreJ2;
    private javax.swing.JTextField scoreJ1;
    private javax.swing.JTextField scoreJ2;
    // End of variables declaration//GEN-END:variables
}
